# Generated by Django 2.2.6 on 2020-10-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='users/'),
        ),
    ]
